// main.rs — Entry point. Wires everything together and starts the gRPC server
// over a Unix domain socket so Go can connect to us on the same machine.

use anyhow::Result;
use std::fs;
use tokio::net::UnixListener;
use tokio_stream::wrappers::UnixListenerStream;
use tonic::transport::Server;
use tracing::info;

// Bring in all our modules
mod capture;
mod detectors;
mod grpc_server;

// include_proto! is a macro from tonic that reads the file generated by
// tonic-build (in OUT_DIR) and pastes it into this module at compile time.
// This is how we get ThreatEvent, SecurityEngineServer, etc. as Rust types.
pub mod eliot {
    tonic::include_proto!("eliot");
}

#[tokio::main]  // Spins up the Tokio multi-threaded runtime automatically
async fn main() -> Result<()> {
    // ── Logging setup ────────────────────────────────────────────────────────
    // RUST_LOG=eliot_engine=debug controls what gets shown.
    // If env var isn't set, default to "info" for this crate.
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| {
                    tracing_subscriber::EnvFilter::new("eliot_engine=info")
                }),
        )
        .with_target(true)   // show which module emitted the log
        .with_thread_ids(true) // show tokio thread ID — useful for async debugging
        .init();

    // ── Socket path ──────────────────────────────────────────────────────────
    // We communicate with Go over a Unix Domain Socket (UDS).
    // UDS is faster than TCP loopback because it skips the network stack entirely.
    // Go will dial this same path when it connects as a gRPC client.
    let socket_path = std::env::var("ELIOT_SOCKET")
        .unwrap_or_else(|_| "/tmp/eliot-engine.sock".to_string());

    // Always remove a stale socket file from a previous run.
    // If we don't do this, UnixListener::bind will return "address already in use".
    let _ = fs::remove_file(&socket_path);

    info!("🦀 Eliot Rust Security Engine");
    info!("   Socket: {}", socket_path);
    info!("   Run as root or grant /dev/bpf access for packet capture.");

    // ── Build the gRPC service ────────────────────────────────────────────────
    // EngineService implements the SecurityEngine trait generated from our proto.
    let engine_service = grpc_server::EngineService::new();

    // ── Bind Unix socket ──────────────────────────────────────────────────────
    // UnixListener is tokio's async wrapper over POSIX Unix sockets.
    let listener = UnixListener::bind(&socket_path)?;

    // UnixListenerStream wraps the listener so tonic can iterate over
    // incoming connections using the Stream trait.
    let incoming = UnixListenerStream::new(listener);

    info!("Listening on unix:{}", socket_path);

    // ── Start gRPC server ────────────────────────────────────────────────────
    // serve_with_incoming lets us plug in any Stream<Item=TcpStream | UnixStream>
    // instead of the default TCP listener. This is how we get UDS gRPC.
    Server::builder()
        .add_service(
            eliot::security_engine_server::SecurityEngineServer::new(engine_service),
        )
        .serve_with_incoming(incoming)
        .await?;

    Ok(())
}